name: Innovative Visions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9207
title: Make Up Artistry by Tawna Coose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2332'
    - '#dee2ef'
    - '#ff7697'
    - '#bd1622'
    - '#7b97a3'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.8127142698504031
  rhythmicContrast: 0.5
purpose: []
