name: Innovative Visions
favicon: null
layout_spectrum: 0.91736
typography_spectrum: 0.9207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe0003'
    - '#5e6a68'
    - '#f5ccc1'
    - '#de8a84'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8127142698504031
  rhythmicContrast: 0.5
purpose: []
